// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcxWLSm4yd_x1YQ3zCwOPkcDIWPhL6eSU',
    appId: '1:951574419039:web:8d3b72ec2d9aa64a036dea',
    messagingSenderId: '951574419039',
    projectId: 'naturemedix-9d49e',
    authDomain: 'naturemedix-9d49e.firebaseapp.com',
    storageBucket: 'naturemedix-9d49e.appspot.com',
    measurementId: 'G-2K2R47M675',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARVBCJ-DO-jN-K_56X3zzlbkps5ed2OZc',
    appId: '1:951574419039:android:dbac3ac276878e7f036dea',
    messagingSenderId: '951574419039',
    projectId: 'naturemedix-9d49e',
    storageBucket: 'naturemedix-9d49e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9TK8oCZULKxyU2Y7G_LuvUi3MgEZBHkU',
    appId: '1:951574419039:ios:9bdc83fc6600045c036dea',
    messagingSenderId: '951574419039',
    projectId: 'naturemedix-9d49e',
    storageBucket: 'naturemedix-9d49e.appspot.com',
    iosBundleId: 'com.example.naturemedix',
  );
}
